spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nic_validation
    username: root
    password: ICET@1234
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    hibernate:
      ddl-auto: update